In [1]:
import sys
print(sys.executable)

C:\Users\sagar\anaconda3\envs\deep\python.exe


In [4]:
import torch 
import torch.nn as nn

In [9]:
imput =torch.tensor([1.0,2.0,3.0])
neuron=nn.Linear(in_features=3,out_features=1)

In [10]:
output=neuron(imput)


In [11]:
output

tensor([-0.0700], grad_fn=<ViewBackward0>)

In [15]:
neuron.weight @ imput + neuron.bias

tensor([-0.0700], grad_fn=<AddBackward0>)

In [16]:
neuron.weight

Parameter containing:
tensor([[-0.4146,  0.3353, -0.1948]], requires_grad=True)